#!/usr/bin/env bash
#
# x86-boot-state.sh — x86 A/B boot-state helper: the GRUB PERSISTENCE ADAPTER
# over the shared slot-state core (RAUC custom backend data layer +
# GRUB-selector algorithm reference).
#
# SAME A/B + bootcount MODEL (BOOT_ORDER / BOOT_<n>_LEFT), SAME CLI, SAME RAUC
# semantics as RK3588 — because both platforms now execute the SAME code: the
# model, the subcommands and the boot-select algorithm all live in
# ../boot-state-core.sh. This file adds ONLY the grubenv storage.
#
# WHY THIS EXISTS (task 33, decision D1 platform = x86; analogous to D3 on RK3588):
# x86 boots via UEFI -> GRUB. Unlike the staged RK3588 vendor U-Boot
# ENV_IS_NOWHERE — no working fw_setenv, hence the RK text-file backend), GRUB has
# FULL persistent-env support through the `grubenv` block + `grub-editenv`. So the
# A/B state lives in the grubenv file on the EFI System Partition, written by BOTH
# the in-GRUB selector (`grub.cfg`, via load_env/save_env) AND userspace (the RAUC
# adapter, this script, via `grub-editenv`).
#
# WHY a CUSTOM RAUC backend and not RAUC's built-in `bootloader=grub` (a deliberate
# choice, documented in README.md): RAUC's stock grub integration uses a SINGLE
# boolean retry per slot (<slot>_OK / <slot>_TRY). We keep the RK3588 model instead
# — a multi-attempt COUNTDOWN (BOOT_<slot>_LEFT: 3->2->1->0) — so BOTH platforms
# share ONE mental model, ONE adapter interface, and ONE test shape. The price is
# we hand-roll the grubenv glue here; the gain is cross-platform symmetry.
#
# STATE (newline KEY=VALUE inside the grubenv block; grub.cfg `load_env` compatible):
#   BOOT_ORDER=A B        # slot bootnames in priority order (head = primary)
#   BOOT_A_LEFT=3         # remaining boot attempts for slot A (3->2->1->0)
#   BOOT_B_LEFT=3         # remaining boot attempts for slot B
# A slot is "good" while it is in BOOT_ORDER and its *_LEFT > 0; "bad" once *_LEFT
# reaches 0 (or it is removed from BOOT_ORDER). Identical to RAUC's u-boot adapter
# semantics and to the RK3588 backend — only the storage (grubenv) differs.
#
# GRUB-SELECTOR ALGORITHM (`boot-select`) is the userspace twin of grub.cfg: pick
# the first slot in BOOT_ORDER whose *_LEFT > 0, DECREMENT that counter, persist,
# emit "<slot> <rootfs_partlabel>". When all counters are exhausted it falls back to
# the head of BOOT_ORDER (last-resort boot). Keeping the two in lockstep lets
# test-x86-fallback.sh PROVE the failed-boot -> decrement -> fallback behaviour with
# no GRUB, no qemu, no hardware.
#
# NOTE — GRUB has NO ARITHMETIC: GRUB script has only integer COMPARISON (`-gt`) and
# string equality, so on-device the DECREMENT is a bounded string-comparison ladder
# (see grub.cfg.tmpl, generated by install-x86-boot.sh). This userspace twin does the
# real subtraction; the ladder is its GRUB-script equivalent for the configured
# BOOT_ATTEMPTS. test-x86-fallback.sh asserts the two stay equivalent.
#
# The RK3588 selector reached the SAME shape for a different reason, and this note
# used to cite it as the counter-example: U-Boot has `setexpr`, but the board's
# U-Boot is built `# CONFIG_CMD_SETEXPR is not set`, so boot.scr.cmd decrements by
# lookup too. Neither shipped bootloader can do arithmetic — do not "restore" one.
#
# STORAGE BACKEND: prefers the real `grub-editenv` (ships in grub-common on every
# GRUB system — guarantees byte-for-byte compatibility with grub.cfg `load_env`).
# Falls back to a SELF-CONTAINED bash reader/writer that emits a grub-editenv-
# compatible 1024-byte environment block, so this script (and the offline test) run
# anywhere — including hosts with no GRUB tooling installed.
#
# shellcheck shell=bash

set -euo pipefail

# grubenv location + attempt budget are env-overridable (the test points them at a
# tmp file). On device the grubenv sits next to grub.cfg on the ESP so GRUB's
# `load_env` (which reads $prefix/grubenv) and userspace see the SAME file.
GRUBENV_FILE="${CERALIVE_GRUBENV:-/boot/efi/EFI/ceralive/grubenv}"
BOOT_ATTEMPTS="${CERALIVE_BOOT_ATTEMPTS:-3}"
GRUB_EDITENV="${GRUB_EDITENV:-grub-editenv}"

BOOT_STATE_TOOL="x86-boot-state"
# On x86 a `set-state bad` may empty BOOT_ORDER: load_state re-defaults an empty
# grubenv to "A B", so an emptied order self-heals on the next read rather than
# leaving a known-bad slot nominated. Making the two platforms agree here would be
# a behaviour change, so the extraction keeps each side's existing answer.
BOOT_STATE_KEEP_LAST_SLOT=0

# The shared core: beside this file in the repo tree, or at its installed device
# path. CERALIVE_BOOT_STATE_CORE overrides both for a staged/test layout.
BOOT_STATE_CORE="${CERALIVE_BOOT_STATE_CORE:-}"
if [[ -z "${BOOT_STATE_CORE}" ]]; then
  _bs_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  for _bs_candidate in "${_bs_here}/../boot-state-core.sh" \
                       /usr/lib/ceralive/boot-state-core.sh; do
    if [[ -r "${_bs_candidate}" ]]; then BOOT_STATE_CORE="${_bs_candidate}"; break; fi
  done
fi
[[ -r "${BOOT_STATE_CORE}" ]] \
  || { printf 'x86-boot-state: shared boot-state core not found (set CERALIVE_BOOT_STATE_CORE)\n' >&2; exit 1; }
# shellcheck source=../boot-state-core.sh
source "${BOOT_STATE_CORE}"

# ---------------------------------------------------------------------------
# grubenv primitives. Prefer the real grub-editenv (compat guarantee); fall back
# to a self-contained bash implementation of the 1024-byte environment block.
# ---------------------------------------------------------------------------
GRUBENV_HEADER="# GRUB Environment Block"
GRUBENV_SIZE=1024

have_grub_editenv() { command -v "${GRUB_EDITENV}" >/dev/null 2>&1; }

# grubenv_list — print KEY=VALUE lines (no comment/padding lines). awk so an empty
# or missing file is a clean exit 0, never a set -e trip.
grubenv_list() {
  if have_grub_editenv && [[ -f "${GRUBENV_FILE}" ]]; then
    "${GRUB_EDITENV}" "${GRUBENV_FILE}" list
    return 0
  fi
  [[ -f "${GRUBENV_FILE}" ]] || return 0
  awk '/^[A-Za-z_][A-Za-z0-9_]*=/{ print }' "${GRUBENV_FILE}"
}

# grubenv_set KEY=VALUE [KEY=VALUE ...] — merge into the grubenv, preserving any
# other GRUB vars (e.g. saved_entry). grub-editenv merges natively; the bash
# fallback re-reads, merges, and rewrites a compatible block.
grubenv_set() {
  local dir; dir="$(dirname "${GRUBENV_FILE}")"
  mkdir -p "${dir}"
  if have_grub_editenv; then
    [[ -f "${GRUBENV_FILE}" ]] || "${GRUB_EDITENV}" "${GRUBENV_FILE}" create
    "${GRUB_EDITENV}" "${GRUBENV_FILE}" set "$@"
    return 0
  fi
  # --- bash fallback: build a grub-editenv-compatible 1024-byte block ----------
  declare -A _vars=()
  local line key val kv
  while IFS= read -r line; do
    [[ "${line}" == *=* ]] || continue
    key="${line%%=*}"; val="${line#*=}"; _vars["${key}"]="${val}"
  done < <(grubenv_list)
  for kv in "$@"; do
    key="${kv%%=*}"; val="${kv#*=}"; _vars["${key}"]="${val}"
  done

  local content body=""
  # sorted keys -> deterministic output (load_env reads them all; order is cosmetic)
  for key in $(printf '%s\n' "${!_vars[@]}" | sort); do
    body+="${key}=${_vars[$key]}"$'\n'
  done
  content="${GRUBENV_HEADER}"$'\n'"${body}"

  local len="${#content}" pad
  (( len <= GRUBENV_SIZE )) || die "grubenv content (${len}B) exceeds the ${GRUBENV_SIZE}B block"
  pad="$(printf '%*s' "$(( GRUBENV_SIZE - len ))" '' | tr ' ' '#')"

  local tmp="${GRUBENV_FILE}.tmp.$$"
  printf '%s%s' "${content}" "${pad}" >"${tmp}"
  mv -f "${tmp}" "${GRUBENV_FILE}"
}

# ---------------------------------------------------------------------------
# PERSISTENCE — grubenv is the single source of truth; read it into
# BOOT_ORDER / BOOT_A_LEFT / BOOT_B_LEFT, the shared core mutates them in memory,
# then persist.
# ---------------------------------------------------------------------------
load_state() {
  BOOT_ORDER=""; BOOT_A_LEFT=""; BOOT_B_LEFT=""
  local key val
  while IFS='=' read -r key val; do
    val="${val%$'\r'}"
    case "${key}" in
      BOOT_ORDER)  BOOT_ORDER="${val}" ;;
      BOOT_A_LEFT) BOOT_A_LEFT="${val}" ;;
      BOOT_B_LEFT) BOOT_B_LEFT="${val}" ;;
    esac
  done < <(grubenv_list)
  # Defaults make a missing/partial grubenv safe: both slots full budget, A leads.
  [[ -n "${BOOT_ORDER}"  ]] || BOOT_ORDER="A B"
  [[ -n "${BOOT_A_LEFT}" ]] || BOOT_A_LEFT="${BOOT_ATTEMPTS}"
  [[ -n "${BOOT_B_LEFT}" ]] || BOOT_B_LEFT="${BOOT_ATTEMPTS}"
}

store_state() {
  grubenv_set "BOOT_ORDER=${BOOT_ORDER}" "BOOT_A_LEFT=${BOOT_A_LEFT}" "BOOT_B_LEFT=${BOOT_B_LEFT}"
}

boot_state_dump_backend() { printf 'GRUBENV_FILE=%s\n' "${GRUBENV_FILE}"; }

boot_state_usage() {
  {
    printf 'Usage: x86-boot-state <command> [args]   (installed as /usr/bin/ceralive-boot-state)\n'
    boot_state_command_lines
    printf '\ngrubenv:  $CERALIVE_GRUBENV (default %s)\n' "${GRUBENV_FILE}"
    printf 'Attempts: $CERALIVE_BOOT_ATTEMPTS (default %s)\n' "${BOOT_ATTEMPTS}"
    printf 'Backend:  $GRUB_EDITENV (default %s; bash fallback if absent)\n' "${GRUB_EDITENV}"
  } >&2
}

boot_state_main "$@"
