#!/bin/bash
#
# ceralive-hdmirx-edid — write the CeraLive product EDID into the SoC's HDMI-RX
# receiver before anything opens the capture device.
#
# WHY (this is a DRIVER REQUIREMENT, not a tuning knob):
#
#   The Synopsys DesignWare HDMI-RX driver ships with no EDID of its own, and
#   its Kconfig says so in as many words: a real product is expected to load a
#   custom, branded EDID from userspace, and the receiver is deliberately not
#   functional until something does. With no EDID the receiver answers nothing
#   on the DDC lines, so an attached source either falls back to its most
#   conservative mode or refuses to output at all. On a bench that reads as
#   "HDMI capture is broken" rather than as "nobody told the receiver what it
#   is willing to accept".
#
#   The blob this writes is the CeraLive product EDID — generated by
#   tools/gen-hdmirx-edid.py, committed byte-exact and checked in CI. It claims
#   3840x2160p60 as the preferred timing, plus SCDC Present and a 600 MHz
#   maximum TMDS character rate in the HDMI Forum VSDB. That PAIR is what makes
#   4K60 legal for a source to offer; the legacy HDMI VSDB in the same block
#   still reads 300 MHz because that is the HDMI-1.4 ceiling it can express, and
#   "correcting" it is a known trap.
#
# WHY BOOT TIME — AND ONLY BOOT TIME (a documented limitation, not a bug):
#
#   The EDID lives in driver state, not in a device tree this repo owns, so it
#   is gone on every reboot. It is equally gone after a driver unbind/rebind or
#   a module reload, and this unit does NOT observe that and does NOT reapply.
#   A rebind is a bench action; the answer after one is an explicit
#   `systemctl restart ceralive-hdmirx-edid.service`. Making it automatic would
#   mean owning the HPD toggle that VIDIOC_S_EDID performs (the driver drops
#   HPD, waits, writes, raises it again), which must never happen underneath a
#   live capture.
#
# WHY A BOUNDED POLL AND NOT A SLEEP: /dev/hdmirx is a udev symlink created when
# the hdmirx platform driver probes, which happens asynchronously and is ordered
# against nothing this unit can wait on. A fixed sleep would be either too short
# (silently no-op) or a permanent boot tax. This polls to a deadline and then
# decides by APPLICABILITY.
#
# THE APPLICABILITY TABLE — three outcomes, and the middle one is the point:
#
#   1. The device appears            -> apply, read back, verify. Loud on failure.
#   2. Absent, and this IS an rk3588 -> FAIL with the exact diagnostic
#      `hdmirx device absent on rk3588 platform`. This is the Orange Pi 5+
#      probe-failure class — snps_hdmirx aborting with -ETIMEDOUT because that
#      board's BL31 does not route the interrupt the driver needs. The hardware
#      is present and the driver did not bind, so a silent no-op would hide a
#      real defect until someone plugged a camera in on a shoot.
#   3. Absent, and this is NOT an HDMI-RX platform -> clean exit 0. x86 targets
#      have no receiver to program and must not fail a boot over it.
#
# VERIFICATION — WHAT THE IMAGE ACTUALLY SHIPS: `v4l-utils` (v4l2-ctl) is an
# explicit entry in manifests/packages/shared.list, so the apply and read-back
# path is guaranteed on every board. `edid-decode` is a SEPARATE Debian package
# and is in neither shared.list nor development.delta.list, so it is absent on
# production AND debug images. The decision that follows from that: the
# byte-comparison of the read-back against the committed blob is the
# AUTHORITATIVE check, and `edid-decode --check` runs only opportunistically if
# a bench operator happens to have installed it. Do not make the run conditional
# on a tool the image does not carry.
#
# PAD DETERMINATION: `pad=` is MANDATORY in both v4l2-ctl EDID options (see
# `v4l2-ctl --help-edid`), and an HDMI-RX video node exposes exactly one input
# pad, index 0. The script does not guess twice: it asks the driver once through
# the ioctl itself, and a pad-related rejection is fail-closed with its own
# diagnostic rather than retried, because a wrong pad is permanent.
# TODO(todo-11): the exact accepted argument forms are confirmed against
# `v4l2-ctl --help-edid` ON THE BOARD during bench validation. If that run
# produces a correction it is fed back into this script BEFORE any image build —
# treat the two v4l2-ctl invocations below as pinned-but-unconfirmed until then.
#
# Test seams (production uses every default):
#   CERALIVE_HDMIRX_DEV          — capture node       (default /dev/hdmirx)
#   CERALIVE_HDMIRX_EDID         — blob to apply      (default /etc/ceralive/hdmirx.edid)
#   CERALIVE_HDMIRX_WAIT         — poll deadline s    (default 30)
#   CERALIVE_HDMIRX_POLL         — poll interval s    (default 0.25)
#   CERALIVE_HDMIRX_ATTEMPTS     — apply attempts     (default 2)
#   CERALIVE_HDMIRX_SYS_ROOT     — sysfs root         (default /sys)
#   CERALIVE_HDMIRX_DT_ROOT      — device-tree root   (default /proc/device-tree)
#   CERALIVE_HDMIRX_V4L2_CTL     — v4l2-ctl binary    (default v4l2-ctl)
#   CERALIVE_HDMIRX_EDID_DECODE  — edid-decode binary (default edid-decode)

# device-daemon profile (docs/shell-profiles.md): -u and pipefail, deliberately
# NO -e, self-contained log/die — this runs on the board where the repo's lib/
# does not exist, and every probe below must be allowed to fail so the script
# reaches its own decision.
set -uo pipefail

DEV="${CERALIVE_HDMIRX_DEV:-/dev/hdmirx}"
BLOB="${CERALIVE_HDMIRX_EDID:-/etc/ceralive/hdmirx.edid}"
WAIT_SECONDS="${CERALIVE_HDMIRX_WAIT:-30}"
POLL_INTERVAL="${CERALIVE_HDMIRX_POLL:-0.25}"
ATTEMPTS="${CERALIVE_HDMIRX_ATTEMPTS:-2}"
SYS_ROOT="${CERALIVE_HDMIRX_SYS_ROOT:-/sys}"
DT_ROOT="${CERALIVE_HDMIRX_DT_ROOT:-/proc/device-tree}"
V4L2_CTL="${CERALIVE_HDMIRX_V4L2_CTL:-v4l2-ctl}"
EDID_DECODE="${CERALIVE_HDMIRX_EDID_DECODE:-edid-decode}"

# The one input pad of an HDMI-RX video node. Not env-overridable on purpose:
# a pad this script cannot program is a driver fact to be reported, not a knob.
PAD=0

# Vendor BSP calls the receiver's platform driver rk_hdmirx; mainline calls the
# same IP block's upstream driver snps_hdmirx. Both are legitimate; anything
# else means /dev/hdmirx points somewhere it should not and is fail-closed.
HDMIRX_DRIVERS_RE='^(rk_hdmirx|snps_hdmirx)$'

log() { printf 'ceralive-hdmirx-edid: %s\n' "$*"; }
die() { printf 'ceralive-hdmirx-edid: %s\n' "$*" >&2; exit 1; }

[[ "${WAIT_SECONDS}" =~ ^[0-9]+$ ]] || die "CERALIVE_HDMIRX_WAIT must be an unsigned integer"
[[ "${ATTEMPTS}" =~ ^[1-9][0-9]*$ ]] || die "CERALIVE_HDMIRX_ATTEMPTS must be a positive integer"

SCRATCH=""
cleanup() {
  if [[ -n "${SCRATCH}" && -d "${SCRATCH}" ]]; then
    rm -rf -- "${SCRATCH}"
  fi
  return 0
}
trap cleanup EXIT

# is_hdmirx_platform — does this board have an HDMI-RX receiver at all?
#
# Two independent signals, either of which is sufficient. The compatible string
# is the general answer (`rockchip,rk3588` covers the whole family). The
# platform-device probe is the specific one, and it matches on the ADDRESS
# rather than the node name because the two kernel trees disagree about the
# name: vendor spells it fdee0000.hdmirx-controller, mainline
# fdee0000.hdmi_receiver. Matching a name would silently answer "no" on one of
# the two trees — the same lesson the rk_hdmirx/snps_hdmirx udev rule records.
is_hdmirx_platform() {
  local compat="${DT_ROOT}/compatible"
  if [[ -r "${compat}" ]]; then
    # /proc/device-tree/compatible is a NUL-separated list of strings.
    if tr '\0' '\n' <"${compat}" | grep -qi 'rockchip,rk3588'; then
      return 0
    fi
  fi

  local dev
  for dev in "${SYS_ROOT}/bus/platform/devices/fdee0000."*; do
    if [[ -e "${dev}" ]]; then
      return 0
    fi
  done

  return 1
}

# node_driver <video4linux-node-dir> — the platform driver bound to a V4L2 node,
# or empty when nothing is bound. Node EXISTENCE is not the question here: the
# udev symlink is driver-keyed, so proving the binding is what proves we are
# talking to the receiver and not to a USB capture card that took the name.
node_driver() {
  local link="$1/device/driver"
  [[ -e "${link}" ]] || return 1
  local target
  target="$(readlink -f -- "${link}")"
  [[ -n "${target}" ]] || return 1
  basename -- "${target}"
}

# ---------------------------------------------------------------------------
# 1. Bounded poll, then the applicability decision.
# ---------------------------------------------------------------------------

deadline=$((SECONDS + WAIT_SECONDS))
while [[ ! -e "${DEV}" ]]; do
  if (( SECONDS >= deadline )); then
    if is_hdmirx_platform; then
      die "hdmirx device absent on rk3588 platform: ${DEV} did not appear within ${WAIT_SECONDS}s — the HDMI-RX driver did not bind (snps_hdmirx probe failure class)"
    fi
    log "no HDMI-RX platform detected and ${DEV} is absent — nothing to program"
    exit 0
  fi
  sleep "${POLL_INTERVAL}"
done

# ---------------------------------------------------------------------------
# 2. Resolve the symlink and prove what it is bound to (fail-closed).
# ---------------------------------------------------------------------------

node_path="$(readlink -f -- "${DEV}")"
[[ -n "${node_path}" && -e "${node_path}" ]] \
  || die "${DEV} does not resolve to a device node"
node="$(basename -- "${node_path}")"

sysfs_node="${SYS_ROOT}/class/video4linux/${node}"
[[ -d "${sysfs_node}" ]] \
  || die "${DEV} -> ${node} has no video4linux class entry at ${sysfs_node}"

driver="$(node_driver "${sysfs_node}")"
[[ -n "${driver}" ]] \
  || die "${DEV} -> ${node} has no bound platform driver"
[[ "${driver}" =~ ${HDMIRX_DRIVERS_RE} ]] \
  || die "${DEV} -> ${node} is bound to '${driver}', not rk_hdmirx/snps_hdmirx — refusing to write an EDID to it"

# Ambiguity is fail-closed: with more than one HDMI-RX-class node present there
# is no way to be sure the symlink resolved to the one an operator means, and
# writing an EDID to the wrong receiver is silent until capture is attempted.
matches=()
for cand in "${SYS_ROOT}/class/video4linux/"*; do
  [[ -d "${cand}" ]] || continue
  cand_driver="$(node_driver "${cand}")"
  [[ -n "${cand_driver}" ]] || continue
  if [[ "${cand_driver}" =~ ${HDMIRX_DRIVERS_RE} ]]; then
    matches+=("$(basename -- "${cand}")")
  fi
done
if (( ${#matches[@]} > 1 )); then
  die "multiple HDMI-RX class nodes present (${matches[*]}) — ambiguous, refusing to guess which one ${DEV} should be"
fi

[[ -s "${BLOB}" ]] || die "EDID blob missing or empty: ${BLOB}"

SCRATCH="$(mktemp -d)"
[[ -n "${SCRATCH}" && -d "${SCRATCH}" ]] || die "could not create a scratch directory for the read-back"

# ---------------------------------------------------------------------------
# 3. Apply + verify, with a bounded retry.
# ---------------------------------------------------------------------------

# pad_rejected <text> — did v4l2-ctl refuse the pad itself? That is permanent,
# so it must break out of the retry loop instead of being tried again.
pad_rejected() {
  printf '%s' "$1" | grep -qi 'pad'
}

apply_once() {
  local attempt="$1"
  local readback="${SCRATCH}/readback.edid"
  local out rc

  rm -f -- "${readback}"

  out="$("${V4L2_CTL}" -d "${DEV}" "--set-edid=pad=${PAD},file=${BLOB},format=raw" 2>&1)"
  rc=$?
  if (( rc != 0 )); then
    if pad_rejected "${out}"; then
      die "hdmirx EDID pad ${PAD} rejected by ${driver} on --set-edid (rc=${rc}): ${out}"
    fi
    log "attempt ${attempt}: --set-edid failed (rc=${rc}): ${out}"
    return 1
  fi

  out="$("${V4L2_CTL}" -d "${DEV}" "--get-edid=pad=${PAD},format=raw,file=${readback}" 2>&1)"
  rc=$?
  if (( rc != 0 )); then
    if pad_rejected "${out}"; then
      die "hdmirx EDID pad ${PAD} rejected by ${driver} on --get-edid (rc=${rc}): ${out}"
    fi
    log "attempt ${attempt}: --get-edid read-back failed (rc=${rc}): ${out}"
    return 1
  fi

  if ! cmp -s -- "${readback}" "${BLOB}"; then
    log "attempt ${attempt}: read-back from ${DEV} is not byte-identical to ${BLOB}"
    return 1
  fi

  # Opportunistic only — see the VERIFICATION note in the header. The image
  # ships no edid-decode, so its absence is normal and never a failure.
  if command -v "${EDID_DECODE}" >/dev/null 2>&1; then
    out="$("${EDID_DECODE}" --check "${readback}" 2>&1)"
    rc=$?
    if (( rc != 0 )); then
      log "attempt ${attempt}: edid-decode --check rejected the read-back (rc=${rc}): ${out}"
      return 1
    fi
    log "read-back passes edid-decode --check"
  else
    log "edid-decode is not installed — the byte-comparison against ${BLOB} is the verification"
  fi

  return 0
}

attempt=1
while (( attempt <= ATTEMPTS )); do
  if apply_once "${attempt}"; then
    log "applied ${BLOB} to ${DEV} -> ${node} (${driver}, pad ${PAD}); read-back verified byte-identical"
    exit 0
  fi
  attempt=$((attempt + 1))
  if (( attempt <= ATTEMPTS )); then
    sleep 1
  fi
done

die "failed to apply ${BLOB} to ${DEV} -> ${node} (${driver}) after ${ATTEMPTS} attempts"
