#!/usr/bin/env bash
#
# x86-boot-state.sh — x86 A/B boot-state read/write helper (RAUC custom backend
# data layer + GRUB-selector algorithm reference). The x86/GRUB twin of the RK3588
# ceralive-boot-state.sh: SAME A/B + bootcount MODEL (BOOT_ORDER / BOOT_<n>_LEFT),
# SAME CLI, SAME RAUC semantics — only the STORAGE backend differs.
#
# WHY THIS EXISTS (task 33, decision D1 platform = x86; analogous to D3 on RK3588):
# x86 boots via UEFI -> GRUB. Unlike the RK3588 vendor U-Boot (2017.09,
# ENV_IS_NOWHERE — no working fw_setenv, hence the RK text-file backend), GRUB has
# FULL persistent-env support through the `grubenv` block + `grub-editenv`. So the
# A/B state lives in the grubenv file on the EFI System Partition, written by BOTH
# the in-GRUB selector (`grub.cfg`, via load_env/save_env) AND userspace (the RAUC
# adapter, this script, via `grub-editenv`).
#
# WHY a CUSTOM RAUC backend and not RAUC's built-in `bootloader=grub` (a deliberate
# choice, documented in README.md): RAUC's stock grub integration uses a SINGLE
# boolean retry per slot (<slot>_OK / <slot>_TRY). We keep the RK3588 model instead
# — a multi-attempt COUNTDOWN (BOOT_<slot>_LEFT: 3->2->1->0) — so BOTH platforms
# share ONE mental model, ONE adapter interface, and ONE test shape. The price is
# we hand-roll the grubenv glue here; the gain is cross-platform symmetry.
#
# STATE (newline KEY=VALUE inside the grubenv block; grub.cfg `load_env` compatible):
#   BOOT_ORDER=A B        # slot bootnames in priority order (head = primary)
#   BOOT_A_LEFT=3         # remaining boot attempts for slot A (3->2->1->0)
#   BOOT_B_LEFT=3         # remaining boot attempts for slot B
# A slot is "good" while it is in BOOT_ORDER and its *_LEFT > 0; "bad" once *_LEFT
# reaches 0 (or it is removed from BOOT_ORDER). Identical to RAUC's u-boot adapter
# semantics and to the RK3588 backend — only the storage (grubenv) differs.
#
# GRUB-SELECTOR ALGORITHM (`boot-select`) is the userspace twin of grub.cfg: pick
# the first slot in BOOT_ORDER whose *_LEFT > 0, DECREMENT that counter, persist,
# emit "<slot> <rootfs_partlabel>". When all counters are exhausted it falls back to
# the head of BOOT_ORDER (last-resort boot). Keeping the two in lockstep lets
# test-x86-fallback.sh PROVE the failed-boot -> decrement -> fallback behaviour with
# no GRUB, no qemu, no hardware.
#
# NOTE — GRUB has NO ARITHMETIC. U-Boot has `setexpr` (real `LEFT = LEFT - 1`); GRUB
# script has only integer COMPARISON (`-gt`) and string equality, so on-device the
# DECREMENT is a bounded string-comparison ladder (see grub.cfg.tmpl, generated by
# install-x86-boot.sh). This userspace twin does the real subtraction; the ladder is
# its GRUB-script equivalent for the configured BOOT_ATTEMPTS. test-x86-fallback.sh
# asserts the two stay equivalent.
#
# STORAGE BACKEND: prefers the real `grub-editenv` (ships in grub-common on every
# GRUB system — guarantees byte-for-byte compatibility with grub.cfg `load_env`).
# Falls back to a SELF-CONTAINED bash reader/writer that emits a grub-editenv-
# compatible 1024-byte environment block, so this script (and the offline test) run
# anywhere — including hosts with no GRUB tooling installed.
#
# shellcheck shell=bash

set -euo pipefail

# grubenv location + attempt budget are env-overridable (the test points them at a
# tmp file). On device the grubenv sits next to grub.cfg on the ESP so GRUB's
# `load_env` (which reads $prefix/grubenv) and userspace see the SAME file.
GRUBENV_FILE="${CERALIVE_GRUBENV:-/boot/efi/EFI/ceralive/grubenv}"
BOOT_ATTEMPTS="${CERALIVE_BOOT_ATTEMPTS:-3}"
GRUB_EDITENV="${GRUB_EDITENV:-grub-editenv}"

# Valid slot bootnames. Symmetric A/B per the frozen partition contract
# (rootfs_a = slot A, rootfs_b = slot B). Single-slot images carry only A.
readonly VALID_SLOTS=("A" "B")

die() { printf 'x86-boot-state: %s\n' "$*" >&2; exit 1; }

# rootfs PARTLABEL for a bootname (contract: slot A -> rootfs_a, slot B -> rootfs_b).
slot_partlabel() {
  case "$1" in
    A) printf 'rootfs_a' ;;
    B) printf 'rootfs_b' ;;
    *) die "unknown slot '$1' (expected A or B)" ;;
  esac
}

is_valid_slot() {
  local s
  for s in "${VALID_SLOTS[@]}"; do [[ "$1" == "${s}" ]] && return 0; done
  return 1
}

# ---------------------------------------------------------------------------
# grubenv primitives. Prefer the real grub-editenv (compat guarantee); fall back
# to a self-contained bash implementation of the 1024-byte environment block.
# ---------------------------------------------------------------------------
GRUBENV_HEADER="# GRUB Environment Block"
GRUBENV_SIZE=1024

have_grub_editenv() { command -v "${GRUB_EDITENV}" >/dev/null 2>&1; }

# grubenv_list — print KEY=VALUE lines (no comment/padding lines). awk so an empty
# or missing file is a clean exit 0, never a set -e trip.
grubenv_list() {
  if have_grub_editenv && [[ -f "${GRUBENV_FILE}" ]]; then
    "${GRUB_EDITENV}" "${GRUBENV_FILE}" list
    return 0
  fi
  [[ -f "${GRUBENV_FILE}" ]] || return 0
  awk '/^[A-Za-z_][A-Za-z0-9_]*=/{ print }' "${GRUBENV_FILE}"
}

# grubenv_set KEY=VALUE [KEY=VALUE ...] — merge into the grubenv, preserving any
# other GRUB vars (e.g. saved_entry). grub-editenv merges natively; the bash
# fallback re-reads, merges, and rewrites a compatible block.
grubenv_set() {
  local dir; dir="$(dirname "${GRUBENV_FILE}")"
  mkdir -p "${dir}"
  if have_grub_editenv; then
    [[ -f "${GRUBENV_FILE}" ]] || "${GRUB_EDITENV}" "${GRUBENV_FILE}" create
    "${GRUB_EDITENV}" "${GRUBENV_FILE}" set "$@"
    return 0
  fi
  # --- bash fallback: build a grub-editenv-compatible 1024-byte block ----------
  declare -A _vars=()
  local line key val kv
  while IFS= read -r line; do
    [[ "${line}" == *=* ]] || continue
    key="${line%%=*}"; val="${line#*=}"; _vars["${key}"]="${val}"
  done < <(grubenv_list)
  for kv in "$@"; do
    key="${kv%%=*}"; val="${kv#*=}"; _vars["${key}"]="${val}"
  done

  local content body=""
  # sorted keys -> deterministic output (load_env reads them all; order is cosmetic)
  for key in $(printf '%s\n' "${!_vars[@]}" | sort); do
    body+="${key}=${_vars[$key]}"$'\n'
  done
  content="${GRUBENV_HEADER}"$'\n'"${body}"

  local len="${#content}" pad
  (( len <= GRUBENV_SIZE )) || die "grubenv content (${len}B) exceeds the ${GRUBENV_SIZE}B block"
  pad="$(printf '%*s' "$(( GRUBENV_SIZE - len ))" '' | tr ' ' '#')"

  local tmp="${GRUBENV_FILE}.tmp.$$"
  printf '%s%s' "${content}" "${pad}" >"${tmp}"
  mv -f "${tmp}" "${GRUBENV_FILE}"
}

# ---------------------------------------------------------------------------
# State load/store. grubenv is the single source of truth; read it into
# BOOT_ORDER / BOOT_A_LEFT / BOOT_B_LEFT, mutate in memory, then persist.
# ---------------------------------------------------------------------------
BOOT_ORDER=""
BOOT_A_LEFT=""
BOOT_B_LEFT=""

load_state() {
  BOOT_ORDER=""; BOOT_A_LEFT=""; BOOT_B_LEFT=""
  local key val
  while IFS='=' read -r key val; do
    val="${val%$'\r'}"
    case "${key}" in
      BOOT_ORDER)  BOOT_ORDER="${val}" ;;
      BOOT_A_LEFT) BOOT_A_LEFT="${val}" ;;
      BOOT_B_LEFT) BOOT_B_LEFT="${val}" ;;
    esac
  done < <(grubenv_list)
  # Defaults make a missing/partial grubenv safe: both slots full budget, A leads.
  [[ -n "${BOOT_ORDER}"  ]] || BOOT_ORDER="A B"
  [[ -n "${BOOT_A_LEFT}" ]] || BOOT_A_LEFT="${BOOT_ATTEMPTS}"
  [[ -n "${BOOT_B_LEFT}" ]] || BOOT_B_LEFT="${BOOT_ATTEMPTS}"
}

store_state() {
  grubenv_set "BOOT_ORDER=${BOOT_ORDER}" "BOOT_A_LEFT=${BOOT_A_LEFT}" "BOOT_B_LEFT=${BOOT_B_LEFT}"
}

left_of() { case "$1" in A) printf '%s' "${BOOT_A_LEFT}" ;; B) printf '%s' "${BOOT_B_LEFT}" ;; esac; }
set_left() { case "$1" in A) BOOT_A_LEFT="$2" ;; B) BOOT_B_LEFT="$2" ;; esac; }

in_order() {
  local s
  for s in ${BOOT_ORDER}; do [[ "${s}" == "$1" ]] && return 0; done
  return 1
}

# ---------------------------------------------------------------------------
# Subcommands (identical surface to the RK3588 ceralive-boot-state.sh).
# ---------------------------------------------------------------------------

# init [--attempts N] [--single-slot] — seed a fresh grubenv. Both slots get the
# full budget; A leads. --single-slot drops B (contract §4 small-media fallback).
cmd_init() {
  local attempts="${BOOT_ATTEMPTS}" single_slot="false"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --attempts)    attempts="${2:?--attempts needs a value}"; shift 2 ;;
      --single-slot) single_slot="true"; shift ;;
      *) die "init: unknown argument '$1'" ;;
    esac
  done
  [[ "${attempts}" =~ ^[0-9]+$ ]] || die "init: --attempts must be a non-negative integer"
  if [[ "${single_slot}" == "true" ]]; then
    BOOT_ORDER="A"; BOOT_A_LEFT="${attempts}"; BOOT_B_LEFT="0"
  else
    BOOT_ORDER="A B"; BOOT_A_LEFT="${attempts}"; BOOT_B_LEFT="${attempts}"
  fi
  store_state
}

cmd_get_order() { load_state; printf '%s\n' "${BOOT_ORDER}"; }

cmd_get_left() {
  local slot="${1:?get-left needs a slot}"; is_valid_slot "${slot}" || die "invalid slot '${slot}'"
  load_state; printf '%s\n' "$(left_of "${slot}")"
}

# get-primary — first slot in BOOT_ORDER with LEFT>0 (the slot that WILL boot). If
# all are exhausted, the head of BOOT_ORDER (last-resort), matching boot-select.
cmd_get_primary() {
  load_state
  local s
  for s in ${BOOT_ORDER}; do
    if (( "$(left_of "${s}")" > 0 )); then printf '%s\n' "${s}"; return 0; fi
  done
  printf '%s\n' "${BOOT_ORDER%% *}"
}

# set-primary <slot> — move <slot> to the FRONT of BOOT_ORDER and reset its budget.
# RAUC calls this to activate a freshly-installed slot.
cmd_set_primary() {
  local slot="${1:?set-primary needs a slot}"; is_valid_slot "${slot}" || die "invalid slot '${slot}'"
  load_state
  local rest="" s
  for s in ${BOOT_ORDER}; do [[ "${s}" == "${slot}" ]] || rest+="${s} "; done
  BOOT_ORDER="$(printf '%s %s' "${slot}" "${rest}" | tr -s ' ')"; BOOT_ORDER="${BOOT_ORDER% }"
  set_left "${slot}" "${BOOT_ATTEMPTS}"
  store_state
}

# get-state <slot> — "good" while in BOOT_ORDER with attempts left; else "bad".
cmd_get_state() {
  local slot="${1:?get-state needs a slot}"; is_valid_slot "${slot}" || die "invalid slot '${slot}'"
  load_state
  if in_order "${slot}" && (( "$(left_of "${slot}")" > 0 )); then
    printf 'good\n'
  else
    printf 'bad\n'
  fi
}

# set-state <slot> good|bad — good: reset attempts (slot proved itself). bad: zero
# attempts AND drop from BOOT_ORDER so the selector skips it.
cmd_set_state() {
  local slot="${1:?set-state needs a slot}" state="${2:?set-state needs good|bad}"
  is_valid_slot "${slot}" || die "invalid slot '${slot}'"
  load_state
  case "${state}" in
    good)
      set_left "${slot}" "${BOOT_ATTEMPTS}"
      in_order "${slot}" || BOOT_ORDER="$(printf '%s %s' "${BOOT_ORDER}" "${slot}" | tr -s ' ')"
      ;;
    bad)
      set_left "${slot}" 0
      local rest="" s
      for s in ${BOOT_ORDER}; do [[ "${s}" == "${slot}" ]] || rest+="${s} "; done
      BOOT_ORDER="$(printf '%s' "${rest}" | tr -s ' ')"; BOOT_ORDER="${BOOT_ORDER% }"
      ;;
    *) die "set-state: state must be 'good' or 'bad' (got '${state}')" ;;
  esac
  store_state
}

# mark-good <slot> — convenience alias of `set-state <slot> good`.
cmd_mark_good() { cmd_set_state "${1:?mark-good needs a slot}" good; }

# boot-select — GRUB-SELECTOR SIMULATION (twin of grub.cfg). Choose the active slot
# (first in BOOT_ORDER with LEFT>0; else head as last resort), DECREMENT its
# counter, persist, print "<slot> <rootfs_partlabel>". Each call models one boot:
# an OS that never mark-good's itself bleeds the counter to 0 and the next call
# falls through to the other slot — automatic rollback.
cmd_boot_select() {
  load_state
  local chosen="" s
  for s in ${BOOT_ORDER}; do
    if (( "$(left_of "${s}")" > 0 )); then chosen="${s}"; break; fi
  done
  if [[ -z "${chosen}" ]]; then
    chosen="${BOOT_ORDER%% *}"
    printf '%s %s\n' "${chosen}" "$(slot_partlabel "${chosen}")"
    return 0
  fi
  set_left "${chosen}" "$(( "$(left_of "${chosen}")" - 1 ))"
  store_state
  printf '%s %s\n' "${chosen}" "$(slot_partlabel "${chosen}")"
}

cmd_dump() {
  load_state
  printf 'GRUBENV_FILE=%s\n' "${GRUBENV_FILE}"
  printf 'BOOT_ORDER=%s\n' "${BOOT_ORDER}"
  printf 'BOOT_A_LEFT=%s\n' "${BOOT_A_LEFT}"
  printf 'BOOT_B_LEFT=%s\n' "${BOOT_B_LEFT}"
}

usage() {
  cat >&2 <<EOF
Usage: x86-boot-state <command> [args]   (installed as /usr/bin/ceralive-boot-state)
  init [--attempts N] [--single-slot]   seed a fresh grubenv A/B state
  get-order                             print BOOT_ORDER
  get-left <A|B>                        print remaining attempts for a slot
  get-primary                           print the slot that will boot
  set-primary <A|B>                     activate a slot (front of order + reset)
  get-state <A|B>                       print "good" or "bad"
  set-state <A|B> <good|bad>            mark a slot good (reset) or bad (drop)
  mark-good <A|B>                       alias of: set-state <A|B> good
  boot-select                           GRUB-selector sim: pick+decrement+persist
  dump                                  print full state

grubenv:  \$CERALIVE_GRUBENV (default ${GRUBENV_FILE})
Attempts: \$CERALIVE_BOOT_ATTEMPTS (default ${BOOT_ATTEMPTS})
Backend:  \$GRUB_EDITENV (default ${GRUB_EDITENV}; bash fallback if absent)
EOF
}

main() {
  local cmd="${1:-}"; shift || true
  case "${cmd}" in
    init)        cmd_init "$@" ;;
    get-order)   cmd_get_order ;;
    get-left)    cmd_get_left "$@" ;;
    get-primary) cmd_get_primary ;;
    set-primary) cmd_set_primary "$@" ;;
    get-state)   cmd_get_state "$@" ;;
    set-state)   cmd_set_state "$@" ;;
    mark-good)   cmd_mark_good "$@" ;;
    boot-select) cmd_boot_select ;;
    dump)        cmd_dump ;;
    -h|--help|"") usage; [[ -n "${cmd}" ]] ;;
    *) usage; die "unknown command '${cmd}'" ;;
  esac
}

main "$@"
